packages:
  - apps/*
  - packages/*

overrides:
  esbuild: ^0.28.1
  find-my-way: ^9.7.0
  "@nestjs/swagger>js-yaml": ^5.2.2
  valibot: ^1.4.2

allowBuilds:
  "@prisma/engines": true
  "@scarf/scarf": true
  argon2: true
  esbuild: true
  prisma: true
  sharp: true

minimumReleaseAgeExclude:
  - "@hookform/resolvers@5.5.7"
